version: '3'

services:
  load_balancer:
  # if github
    image: https://ghcr.io/Kristina2319/solution3/main/apps/nginx/Dockerfile

  app1:
    image: https://ghcr.io/Kristina2319/solution3/main/apps/wordpress/Dockerfile
    ports:
      - 80:80

  app2:
    image: https://ghcr.io/Kristina2319/solution3/main/apps/wordpress/Dockerfile
    ports:
      - 80:80

  db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=rootwordpress
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress
