version: '3'

services:
  load_balancer:
  # if github
    image: ghcr.io/Kristina2319/solution3/blob/main/apps/nginx

  app1:
    image: ghcr.io/Kristina2319/solution3/tree/main/apps/wordpress
    ports:
      - 80:80

  app2:
    image: ghcr.io/Kristina2319/solution3/tree/main/apps/wordpress
    ports:
      - 80:80

  db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=rootwordpress
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress
