version: '3'

services:
  load_balancer:
  # if github
    image: ghcr.io/kristina2319/solution3:nginx
    depends_on:
      - app1
      - app2
     networks:
      - nginx_wordpress

  app1:
    image: ghcr.io/kristina2319/solution3:wordpress
    depends_on:
      - db
     networks:
      - nginx_wordpress
      - wordpress_mysql

  app2:
    image: ghcr.io/kristina2319/solution3:wordpress
    depends_on:
      - db
    networks:
      - nginx_wordpress
      - wordpress_mysql
  db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=rootwordpress
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress
