version: '3'

services:
  load_balancer:
  # if github
    image: ghcr.io/kristina2319/solution3:nginx
    depends_on:
      - app1
      - app2

  app1:
    image: ghcr.io/kristina2319/solution3:wordpress
    depends_on:
      - db
    ports:
      - 80:80

  app2:
    image: ghcr.io/kristina2319/solution3:wordpress
    depends_on:
      - db
    #ports:
      #- 80:80
  db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=rootwordpress
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress
