version: '3'
services:
  nginx:
    image: 
    ports:
      - 80:80
    depends_on:
      - app1
      - app2
    networks:
      - nginx_wordpress
  app1:
    image: 
    volumes:
      - /var/wordpress:/var/www/html
    depends_on:
      - mysql
    networks:
      - nginx_wordpress
      - wordpress_mysql
  app2:
    image: 
    volumes:
      - /var/wordpress:/var/www/html
    depends_on:
      - mysql
    networks:
      - nginx_wordpress
      - wordpress_mysql
  mysql:
    image:
    volumes:
      - /var/mysql:/var/lib/mysql
    networks:
      - wordpress_mysql
networks:
  nginx_wordpress:
    driver: bridge
  wordpress_mysql:
    driver: bridge
